/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "../Inc/LIB/STD_TYPES.h"
#include "../Inc/LIB/BIT_MATH.h"

#include "../Inc/MCAL/RCC/RCC_interface.h"
#include "../Inc/MCAL/GPIO/GPIO_interface.h"
#include "../Inc/MCAL/UART/UART_interface.h"
#include "../Inc/MCAL/NVIC/NVIC_interface.h"
#include "../Inc/MCAL/CRC/CRC_interface.h"
#include "../Inc/MCAL/FLASH/flash_interface.h"
#include "../Inc/Bootloader/bootloader.h"

extern u32 PAGE_ARRAY[];

int main(void)
{
BL_StatusType CommandStatus = BL_NACK;

	/*RCC init*/
 	MRCC_voidInit();
	MRCC_voidPreipheralEnable(APB2, IOPA_ENABLE_BIT);
	MRCC_voidPreipheralEnable(AHB,  CRCEN_ENABLE_BIT);
	MRCC_voidPreipheralEnable(APB2, USART1_ENABLE_BIT);
	MRCC_voidPreipheralEnable(APB1, USART2_ENABLE_BIT);


	MGPIO_voidSetPinDirection(GPIO_U8_PORTA,GPIO_U8_PIN9,GPIO_OUTPUT_AF_PP_50MHZ);
	MGPIO_voidSetPinDirection(GPIO_U8_PORTA,GPIO_U8_PIN10,GPIO_INPUT_FLOATING);

	MGPIO_voidSetPinDirection(GPIO_U8_PORTA,GPIO_U8_PIN2,GPIO_OUTPUT_AF_PP_50MHZ);
	MGPIO_voidSetPinDirection(GPIO_U8_PORTA,GPIO_U8_PIN3,GPIO_INPUT_FLOATING);


	//UART init
	MUART_voidInit(UART_1);
	MUART_voidInit(UART_2);

	for(;;)
	{
		
#ifdef BL_DEBUG_INFO
 	BL_Print_Message("Bootloader Started ..\n");
#endif
		CommandStatus = BL_UART_Featch_Host_Command();
	}



}
